name = "voxpro-waitlist-worker"
main = "src/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# KV Namespace binding
kv_namespaces = [
  { binding = "WAITLIST", id = "20b5411f4aaa48b1813507383bae3b93" }
]

# Environment variables will be set in the Cloudflare dashboard
[vars]

# Enable logs
[build]
command = ""
watch_dir = "src"

[triggers]
crons = []

[observability.logs]
enabled = true

[[send_email]]
name = "WAITLIST_EMAIL"
destination_address = "waitlist@voxpro.app"
