name = "voxpro-waitlist-worker"
main = "src/index.js"
compatibility_date = "2024-03-14"

# KV Namespace binding
kv_namespaces = [
  { binding = "WAITLIST", id = "c2cf2f306479978d46f122ba5c128e9e" }
]

# Environment variables will be set in the Cloudflare dashboard
[vars]
# RESEND_API_KEY = "your-api-key-here"

# Enable logs
[build]
command = ""
watch_dir = "src"

[triggers]
crons = []

[observability.logs]
enabled = true
